
service: trouttracker
app: trouttracker
org: yoursweater

provider:
  name: aws
  runtime: python3.8
  profile: daneversen
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:us-east-1:589745751216:table/fishTable"
    - Effect: "Allow"
      Action:
        - "dynamodb:DescribeTable"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: "arn:aws:dynamodb:us-east-1:589745751216:table/flyTable"

resources:
  Resources:
    fishTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: fishTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    flyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: flyTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

functions:
  addfish:
    handler: handler.addfish
    events:
      - http:
          path: /addfish
          method: post
  addfly:
    handler: handler.addfly
    events:
      - http:
          path: /addfly
          method: post
  getflies:
    handler: handler.getflies
    events:
      - http:
          path: /getflies
          method: get
  getfish:
    handler: handler.getfish
    events:
      - http:
          path: /getfish
          method: get
